# Generated by Django 5.0.2 on 2024-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texthandler', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Snippet Content'),
        ),
    ]
